### 1. Pandas Version

In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.2.3'

In [4]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-23 15:13:36--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: 'car_fuel_efficiency.csv'

     0K .......... .......... .......... .......... ..........  5%  365K 2s
    50K .......... .......... .......... .......... .......... 11%  720K 2s
   100K .......... .......... .......... .......... .......... 17% 16.3M 1s
   150K .......... .......... .......... .......... .......... 23% 19.5M 1s
   200K .......... .......... .......... .......... .......... 29%  722K 1s
   250K .......... .......... .......... .......... .......... 35% 17.4M 1s
   300K .......... .......... .......... .......... .......... 40% 25.7M 0s
   350K .

In [6]:
df = pd.read_csv('car_fuel_efficiency.csv')

### 2. Records Count

In [9]:
df.shape

(9704, 11)

### 3. Fuel types

In [11]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [13]:
df.fuel_type.nunique()

2

### 4. Missing values

In [17]:
(df.isnull().sum() > 0).sum()

np.int64(4)

### 5. Max fuel efficiency

In [29]:
categorical = list(df.columns[(df.dtypes == 'object')])

In [31]:
for col in categorical:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [32]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  europe  gasoline    all-wheel_drive        0.0   
1          17.8        2007     usa  gasoline  front-wheel_drive        0.0   
2          15.1        2018  europe  gasoline  front-wheel_drive        0.0   
3          20.2        2009     usa    diesel    all-wheel_drive        2.0   
4          14.4        2009  europe  gasoline    all-wheel_drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [33]:
df[df.origin == 'asia'].fuel_efficiency_mpg.max()

23.759122836520497

### 6. Median Value of horsepower

In [36]:
md = df.horsepower.median()
md

149.0

In [47]:
most_freq = df.horsepower.value_counts().index[0]
print(most_freq)

152.0


In [49]:
df.horsepower.isnull().sum()

np.int64(708)

In [50]:
df.horsepower.fillna(152.0, inplace=True)

In [51]:
df.horsepower.median()

152.0

### 7. Sum of weights

In [55]:
columns = ['vehicle_weight', 'model_year']
X = df[df.origin == 'asia'][columns].iloc[:7].values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [56]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [58]:
import numpy as np
invXTX = np.linalg.inv(XTX)
invXTX

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [59]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [60]:
w = invXTX.dot(X.T).dot(y)
w

array([0.01386421, 0.5049067 ])

In [61]:
w.sum()

np.float64(0.5187709081074007)